
import { Product, User, Coupon, SecurityLog } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Wireless Noise-Cancelling Headphones Pro',
    category: 'Electronics',
    price: 299.00,
    rating: 4.8,
    reviews: 128,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop',
    thumbnails: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=200', 'https://images.unsplash.com/photo-1583394838336-acd977736f90?q=80&w=200'],
    stockStatus: 'In Stock',
    stockQuantity: 45,
    minStock: 10,
    sku: 'AUDIO-001',
    description: 'Experience sound like never before with our latest driver technology. Immerse yourself in pure audio bliss with active noise cancellation and a comfortable, ergonomic fit designed for all-day wear.'
  },
  {
    id: '2',
    name: 'Classic Vintage Denim Jacket',
    category: 'Fashion',
    price: 89.50,
    rating: 4.5,
    reviews: 45,
    image: 'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'In Stock',
    stockQuantity: 20,
    minStock: 5,
    sku: 'FASH-002',
    description: 'A timeless classic. This vintage denim jacket features a relaxed fit, durable cotton denim, and signature metal buttons. Perfect for layering in any season.'
  },
  {
    id: '3',
    name: 'Minimalist Ceramic Vase',
    category: 'Home Decor',
    price: 45.00,
    rating: 5.0,
    reviews: 210,
    image: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'In Stock',
    stockQuantity: 100,
    minStock: 15,
    sku: 'HOME-003',
    description: 'Elevate your living space with this handcrafted ceramic vase. Its minimalist design and smooth matte finish make it a perfect centerpiece for any modern home.'
  },
  {
    id: '4',
    name: 'Series 7 Smart Watch',
    category: 'Electronics',
    price: 349.00,
    originalPrice: 399.00,
    rating: 4.7,
    reviews: 89,
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'In Stock',
    stockQuantity: 12,
    minStock: 10,
    sku: 'WATCH-X24',
    description: 'Stay connected and active with the Series 7 Smart Watch. Featuring an always-on retina display, advanced health monitoring, and water resistance up to 50 meters.'
  },
  {
    id: '5',
    name: 'Air Max Runner Sport',
    category: 'Footwear',
    price: 120.00,
    rating: 4.9,
    reviews: 342,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'Out of Stock',
    stockQuantity: 0,
    minStock: 8,
    sku: 'SHOE-R99',
    description: 'Designed for the dedicated runner. These shoes provide superior cushioning and energy return, helping you run further and faster with less fatigue.'
  },
  {
    id: '6',
    name: 'Scandanavian Grey Sofa',
    category: 'Home Decor',
    price: 899.00,
    rating: 4.2,
    reviews: 18,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'In Stock',
    stockQuantity: 5,
    minStock: 2,
    sku: 'HOME-SOFA',
    description: 'Bring comfort and style to your living room with this Scandinavian-inspired sofa. Upholstered in premium grey fabric with solid wood legs.'
  },
  {
    id: '7',
    name: 'Instant Film Camera',
    category: 'Electronics',
    price: 119.00,
    rating: 4.6,
    reviews: 56,
    image: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'Low Stock',
    stockQuantity: 3,
    minStock: 5,
    sku: 'CAM-POL1',
    description: 'Capture memories instantly with this retro-styled film camera. Features automatic exposure measurement and a built-in selfie lens and mirror.'
  },
  {
    id: '8',
    name: 'Ultra-Slim 14" Laptop',
    category: 'Electronics',
    price: 1299.00,
    rating: 4.9,
    reviews: 76,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'In Stock',
    stockQuantity: 15,
    minStock: 3,
    sku: 'TECH-LAP14',
    description: 'Power meets portability. This ultra-slim laptop features the latest processor, a stunning 4K display, and all-day battery life for professionals on the go.'
  },
  {
    id: '9',
    name: 'Summer Floral Maxi Dress',
    category: 'Fashion',
    price: 59.99,
    originalPrice: 79.99,
    rating: 4.4,
    reviews: 215,
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'In Stock',
    stockQuantity: 60,
    minStock: 10,
    sku: 'FASH-DRS1',
    description: 'Breezy and beautiful. This floral maxi dress is perfect for summer days and beach vacations. Made from breathable linen blend fabric.'
  },
  {
    id: '10',
    name: 'Modern Bamboo Plant Stand',
    category: 'Home Decor',
    price: 34.50,
    rating: 4.8,
    reviews: 92,
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'In Stock',
    stockQuantity: 32,
    minStock: 5,
    sku: 'HOME-PLNT',
    description: 'Display your greenery in style. This mid-century modern inspired plant stand is crafted from sustainable bamboo and fits pots up to 10 inches.'
  },
  {
    id: '11',
    name: 'Leather Oxford Loafers',
    category: 'Footwear',
    price: 145.00,
    rating: 4.7,
    reviews: 34,
    image: 'https://images.unsplash.com/photo-1614252369475-531eba835eb1?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'Low Stock',
    stockQuantity: 4,
    minStock: 8,
    sku: 'SHOE-OXF',
    description: 'Handcrafted genuine leather loafers. These shoes offer sophisticated style and superior comfort with a cushioned insole and durable rubber outsole.'
  },
  {
    id: '12',
    name: '4K Ultra HD Monitor',
    category: 'Electronics',
    price: 499.00,
    rating: 4.6,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'In Stock',
    stockQuantity: 22,
    minStock: 5,
    sku: 'TECH-MON4K',
    description: 'See every detail with our 27-inch 4K monitor. Perfect for designers and gamers alike, offering 99% sRGB color accuracy and 144Hz refresh rate.'
  },
  {
    id: '13',
    name: 'Aviator Sunglasses',
    category: 'Accessories',
    price: 150.00,
    rating: 4.8,
    reviews: 440,
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'In Stock',
    stockQuantity: 80,
    minStock: 15,
    sku: 'ACC-SUN1',
    description: 'Classic style that never fades. These aviator sunglasses feature polarized lenses and a lightweight metal frame for maximum comfort and UV protection.'
  },
  {
    id: '14',
    name: 'Abstract Geometric Rug',
    category: 'Home Decor',
    price: 199.00,
    rating: 4.3,
    reviews: 28,
    image: 'https://images.unsplash.com/photo-1575414003591-ece8d0416c7a?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'In Stock',
    stockQuantity: 14,
    minStock: 3,
    sku: 'HOME-RUG',
    description: 'Add a pop of color and texture to your floor. This soft, durable rug features a bold geometric pattern that complements modern interiors.'
  },
  {
    id: '15',
    name: 'Smart Home Speaker',
    category: 'Electronics',
    price: 99.00,
    rating: 4.5,
    reviews: 882,
    image: 'https://images.unsplash.com/photo-1589492477829-5e65395b66cc?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'In Stock',
    stockQuantity: 150,
    minStock: 20,
    sku: 'TECH-SPK',
    description: 'Your personal assistant and music hub in one. Control your smart home devices, play music, and get answers with just your voice.'
  },
  {
    id: '16',
    name: 'Retro Mechanical Keyboard',
    category: 'Electronics',
    price: 165.00,
    rating: 4.7,
    reviews: 89,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b91add1?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'In Stock',
    stockQuantity: 25,
    minStock: 5,
    sku: 'TECH-KB01',
    description: 'Clicky, tactile, and stylish. This retro-inspired mechanical keyboard features typewriter-style keycaps and RGB backlighting.'
  },
  {
    id: '17',
    name: 'Leather Crossbody Bag',
    category: 'Fashion',
    price: 110.00,
    rating: 4.6,
    reviews: 120,
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'In Stock',
    stockQuantity: 40,
    minStock: 8,
    sku: 'FASH-BAG2',
    description: 'The perfect daily companion. Made from premium vegetable-tanned leather that ages beautifully over time.'
  },
  {
    id: '18',
    name: 'Marble Coffee Table',
    category: 'Home Decor',
    price: 450.00,
    rating: 4.8,
    reviews: 32,
    image: 'https://images.unsplash.com/photo-1532372320572-cda25653a26d?q=80&w=1000&auto=format&fit=crop',
    stockStatus: 'Low Stock',
    stockQuantity: 3,
    minStock: 3,
    sku: 'HOME-TBL',
    description: 'Luxury for your living room. This solid marble coffee table features a sleek metal base and a polished white marble top.'
  }
];

export const USERS: User[] = [
  { id: '1', name: 'Duy admin', email: 'duyadmin@gmail.com', role: 'Admin', status: 'Active', lastLogin: '2 mins ago', avatar: 'https://picsum.photos/id/64/100/100' },
  { id: '2', name: 'Duy Staff', email: 'duystaff@gmail.com', role: 'Staff', status: 'Active', lastLogin: '3 hours ago', avatar: 'https://picsum.photos/id/65/100/100' },
  { id: '3', name: 'Duy Khach Hang', email: 'duykhachhang@gmail.com', role: 'Customer', status: 'Inactive', lastLogin: '1 day ago', avatar: 'https://picsum.photos/id/66/100/100' },
  { id: '4', name: 'Cameron Williamson', email: 'cameron.w@example.com', role: 'Customer', status: 'Active', lastLogin: '2 days ago', avatar: 'https://picsum.photos/id/67/100/100' },
  { id: '5', name: 'Jane Cooper', email: 'jane.cooper@example.com', role: 'Admin', status: 'Active', lastLogin: '10 mins ago', avatar: 'https://picsum.photos/id/68/100/100' },
  { id: '6', name: 'Esther Howard', email: 'esther.howard@example.com', role: 'Customer', status: 'Active', lastLogin: '5 hours ago', avatar: 'https://picsum.photos/id/69/100/100' },
];

export const COUPONS: Coupon[] = [
  { id: '1', code: 'SUMMER2024', description: 'End of season sale', type: 'Percentage', value: 20, usageCount: 145, usageLimit: 500, expiryDate: 'Aug 31, 2024', status: 'Active' },
  { id: '2', code: 'WELCOME10', description: 'New user bonus', type: 'Fixed Cart', value: 10, usageCount: 0, usageLimit: 0, expiryDate: 'No Expiry', status: 'Active' },
  { id: '3', code: 'FLASH50', description: '24hr Flash Sale', type: 'Percentage', value: 50, usageCount: 50, usageLimit: 50, expiryDate: 'Yesterday', status: 'Expired' },
  { id: '4', code: 'FREESHIP', description: 'Free shipping > $50', type: 'Free Shipping', value: 0, usageCount: 1203, usageLimit: 0, expiryDate: 'Dec 31, 2024', status: 'Active' },
  { id: '5', code: 'VIP25', description: 'Loyalty Rewards', type: 'Percentage', value: 25, usageCount: 12, usageLimit: 100, expiryDate: 'Oct 15, 2024', status: 'Scheduled' },
];

export const SECURITY_LOGS: SecurityLog[] = [
  { id: '1', type: 'Warning', title: 'Failed Login Attempt', detail: 'IP 192.168.1.42 • 10m ago' },
  { id: '2', type: 'Info', title: 'System Updated', detail: 'Core v2.4.1 • 2h ago' },
  { id: '3', type: 'Success', title: 'Backup Completed', detail: 'Automated • 5h ago' },
];
